// <auto-generated />
using System;
using MaarifPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MaarifPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaarifDbContext))]
    partial class MaarifDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.AiRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Provider");

                    b.HasIndex("QuestionId");

                    b.HasIndex("Stage");

                    b.ToTable("ai_runs", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.AlignmentScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Criterion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCriticalGate")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionVersionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.ToTable("alignment_scores", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.BookPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUri")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("OcrUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("PageNo")
                        .HasColumnType("integer");

                    b.Property<string>("RawText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "PageNo")
                        .IsUnique();

                    b.ToTable("book_pages", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.Distractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<bool>("IsHypothesis")
                        .HasColumnType("boolean");

                    b.Property<string>("MisconceptionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("QuestionVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.ToTable("distractors", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.LearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<Guid>("MaarifStandardVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaarifStandardVersionId");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("Code", "MaarifStandardVersionId")
                        .IsUnique();

                    b.ToTable("learning_outcomes", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.MaarifStandardVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("maarif_standard_versions", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("prompt_templates", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookPageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MaarifStandardVersionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("QuestionNo")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("BookPageId");

                    b.HasIndex("MaarifStandardVersionId");

                    b.HasIndex("Status");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.QuestionDna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AiEstimatedStudentTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("AlignmentIssuesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CognitiveLevel")
                        .HasColumnType("text");

                    b.Property<string>("ConceptualSkill")
                        .HasColumnType("text");

                    b.Property<string>("ContextQuality")
                        .HasColumnType("text");

                    b.Property<string>("ContextType")
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DnaSchemaVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EditorRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ExpectedSolutionSteps")
                        .HasColumnType("text");

                    b.Property<string>("ExtensionsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("FieldSkill")
                        .HasColumnType("text");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("LearningOutcome")
                        .HasColumnType("text");

                    b.Property<string>("LearningOutcomeCode")
                        .HasColumnType("text");

                    b.Property<int?>("MaarifAlignmentScore")
                        .HasColumnType("integer");

                    b.Property<string>("MathematicalCore")
                        .HasColumnType("text");

                    b.Property<string>("NewOptionsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("NewQuestion")
                        .HasColumnType("text");

                    b.Property<string>("OriginalAnswer")
                        .HasColumnType("text");

                    b.Property<string>("OriginalOptionsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OriginalQuestion")
                        .HasColumnType("text");

                    b.Property<string>("OriginalVisualReference")
                        .HasColumnType("text");

                    b.Property<string>("ProcessComponent")
                        .HasColumnType("text");

                    b.Property<string>("QualityFlagsJson")
                        .HasColumnType("jsonb");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionType")
                        .HasColumnType("text");

                    b.Property<Guid>("QuestionVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasoningTypesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RepresentationTypesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Solution")
                        .HasColumnType("text");

                    b.Property<string>("SourceBook")
                        .HasColumnType("text");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<string>("SourceReferencesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("Subtopic")
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<string>("TransformationLevel")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("LearningOutcomeCode");

                    b.HasIndex("QuestionVersionId")
                        .IsUnique();

                    b.ToTable("question_dna", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.QuestionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "VersionNo")
                        .IsUnique();

                    b.ToTable("question_versions", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.ReferenceChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<int?>("Page")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReferenceDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceDocumentId");

                    b.ToTable("reference_chunks", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.ReferenceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("PublicationDate")
                        .HasColumnType("date");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentHash")
                        .IsUnique();

                    b.ToTable("reference_documents", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.ReviewQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonFlagsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("Status", "Priority");

                    b.ToTable("review_queue", (string)null);
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.AiRun", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.AlignmentScore", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.QuestionVersion", "QuestionVersion")
                        .WithMany("AlignmentScores")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.BookPage", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.Book", "Book")
                        .WithMany("Pages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.Distractor", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.QuestionVersion", "QuestionVersion")
                        .WithMany("Distractors")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.LearningOutcome", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.MaarifStandardVersion", "MaarifStandardVersion")
                        .WithMany()
                        .HasForeignKey("MaarifStandardVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaarifPlatform.Domain.Entities.ReferenceDocument", "SourceDocument")
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaarifStandardVersion");

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.Question", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.Book", "Book")
                        .WithMany("Questions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaarifPlatform.Domain.Entities.BookPage", "BookPage")
                        .WithMany()
                        .HasForeignKey("BookPageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MaarifPlatform.Domain.Entities.MaarifStandardVersion", "MaarifStandardVersion")
                        .WithMany()
                        .HasForeignKey("MaarifStandardVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Book");

                    b.Navigation("BookPage");

                    b.Navigation("MaarifStandardVersion");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.QuestionDna", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.QuestionVersion", "QuestionVersion")
                        .WithOne("Dna")
                        .HasForeignKey("MaarifPlatform.Domain.Entities.QuestionDna", "QuestionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.QuestionVersion", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.Question", "Question")
                        .WithMany("Versions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.ReferenceChunk", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.ReferenceDocument", "ReferenceDocument")
                        .WithMany("Chunks")
                        .HasForeignKey("ReferenceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenceDocument");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.ReviewQueueItem", b =>
                {
                    b.HasOne("MaarifPlatform.Domain.Entities.AppUser", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MaarifPlatform.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.Book", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.Question", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.QuestionVersion", b =>
                {
                    b.Navigation("AlignmentScores");

                    b.Navigation("Distractors");

                    b.Navigation("Dna");
                });

            modelBuilder.Entity("MaarifPlatform.Domain.Entities.ReferenceDocument", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
